/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package angelcatalogomelanie;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSetMetaData;
import com.mysql.jdbc.Statement;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FGG
 */
public class TablasJoyas extends javax.swing.JFrame {
DefaultTableModel model;
ResultSetMetaData rsMt;
float n1,n2,n3,n4;
String cantidad,descripcion,codigo,precio,total,sql="";
 protected Statement st = null;

    /**
     * Creates new form TablasJoyas
     */
    public TablasJoyas() {
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/img/42349585.jpg")).getImage());
         setLocationRelativeTo(null);
         limpiarjoyas();
         bloquearjoyas();
         mostrarJoyas();
    }
 
    public void imprimir()
 {
     try
     {
         MessageFormat headerFormat= new MessageFormat("MelanieCatalogo");
         MessageFormat footerFormat= new MessageFormat("MelanieCatalogo");
         tablaJoyas.print(JTable.PrintMode.FIT_WIDTH, headerFormat, footerFormat);
     }
     catch(PrinterException ex)
     {
       Logger.getLogger(RegistroClientes.class.getName()).log(Level.SEVERE, null, ex);       
     }
 }
  private void  mostrarJoyas()
   {
     DefaultTableModel model = new DefaultTableModel();               
        ResultSet rs = Conectar.getTabla("select * from joyas");
        model.setColumnIdentifiers(new Object[]{"cantidad", "descripcion","codigo","precio","total"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                model.addRow(new Object[]{rs.getString("cantidad"), rs.getString("descripcion"),rs.getString("codigo"),rs.getString("precio"),rs.getString("total")});
            }            
            // asigna el modelo a la tabla
            tablaJoyas.setModel(model);            
        } catch (Exception e) {
            System.out.println(e);
        }  
   }
  public void resultado()
  {
      n1=Float.parseFloat(cantidad);
      n2=Float.parseFloat(precio);
      n3=Float.parseFloat(total);
     n3=n1*n2;
     total = Float.toString(n3); 
    lblTotal.setText(total);
  }
  public void limpiarjoyas()
{
   txtCantidad.setText("");
   txtCodigo.setText("");
   txtDescripcion.setText("");
   txtPrecio.setText("");
   }
   public void bloquearjoyas()
{
   txtCantidad.setEnabled(false);
   txtCodigo.setEnabled(false);
   txtDescripcion.setEnabled(false);
  txtPrecio.setEnabled(false);
  btnRegistrar.setEnabled(false);
  btnModificar.setEnabled(false);
  btnEliminar.setEnabled(false);
  btnImprimir.setEnabled(false);
}
public void desbloquearjoyas()
{
   txtCantidad.setEnabled(true);
   txtCodigo.setEnabled(true);
   txtDescripcion.setEnabled(true);
  txtPrecio.setEnabled(true);
   btnRegistrar.setEnabled(true);
  btnModificar.setEnabled(true);
  btnEliminar.setEnabled(true);
  btnImprimir.setEnabled(true);
}

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaJoyas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setUndecorated(true);

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnImprimir.setText("IMPRIMIR");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tablaJoyas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cantidad", "descripcion", "codigo", "precio", "total"
            }
        ));
        tablaJoyas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJoyasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaJoyas);

        jLabel1.setText("Cantidad:");

        jLabel2.setText("Descripción:");

        jLabel3.setText("Código");

        jLabel4.setText("Precio:");

        jLabel5.setText("Total:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/joyasdos.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("TABLA DE JOYAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnImprimir)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addComponent(txtCodigo)
                                            .addComponent(txtCantidad)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnSalir)
                    .addComponent(btnImprimir)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
  ////////////////////////////////CONEXION DIRECTA A MYSQL
        Conectar cc=new Conectar();
 Connection cn= (Connection) cc.conexion();
 ///////////////////////////////// LUGAR DONDE SE TOMAN LOS REGISTROS A GUARDAR  
 cantidad=txtCantidad.getText();
  descripcion=txtDescripcion.getText();
   codigo=txtCodigo.getText();
   precio=txtPrecio.getText();
  total = Float.toString(n3); 
    lblTotal.setText(total); 
 /////////////////////////////////METODO PARA CALCULAR EL RESULTADO ANTES DE GUARDAR EN LAS TABLAS
 resultado();
  ///////////////////////////////INICIO DE LA SENTENCIA SQL, CON TRY AND CATCH   
  sql="INSERT INTO joyas(cantidad,descripcion,codigo,precio,total) VALUES (?,?,?,?,?)";
    try {
         if (tablaJoyas.getRowCount() == 0 )
{
}
else
{
   JOptionPane.showMessageDialog(tablaJoyas, "FAVOR DE INTRODUCIR DATOS PARA GUARDAR" , "REGISTROS VACIOS", JOptionPane.ERROR_MESSAGE);
    
}
        java.sql.PreparedStatement pst= cn.prepareStatement(sql);
     pst.setString(1,cantidad);
    pst.setString(2,descripcion);
    pst.setString(3,codigo);
    pst.setString(4,precio);
    pst.setString(5,"$"+lblTotal);
     pst.executeUpdate();
     JOptionPane.showMessageDialog(null, "REGISTROS GUARDADOS ");
    }
    catch (SQLException ex) 
    {
    Logger.getLogger(TablasJoyas.class.getName()).log(Level.SEVERE, null,ex);
      
    }
  /////////////////////////////////////////TERMINA LA SENTENCIA SQL 
  ////////////////////////////////////////METODO PARA VISUALIZAR LA TABLA DE JOYAS DESPUES DE ACTUALIZAR
    mostrarJoyas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
RegistroClientes rc = new RegistroClientes();
rc.setVisible(true); 
this.show(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
imprimir();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
  Conectar cc=new Conectar();
 Connection cn= (Connection) cc.conexion();
 try
{
         if (tablaJoyas.equals(null) )
{
}
  else
{
   JOptionPane.showMessageDialog(null, "NO SE PUEDEN MODIFICAR LOS CAMPOS SELECCIONADOS" , "REGISTROS VACIOS", JOptionPane.ERROR_MESSAGE);
    //return;
}
    java.sql.PreparedStatement pst = cn.prepareStatement(sql="UPDATE joyas set cantidad='"+txtCantidad.getText()+"', descripcion='"+txtDescripcion.getText()+"' codigo='"+txtCodigo.getText()+"', precio='"+txtPrecio.getText()+"',  where cantidad='"+txtCantidad.getText()+"'");
pst.executeUpdate();
  
 JOptionPane.showMessageDialog(null, "DATOS MODIFICADOS CORRECTAMENTE"); 
     resultado();
}
    catch (SQLException ex) {
    Logger.getLogger(TablasJoyas.class.getName()).log(Level.SEVERE, null, ex);
    }
mostrarJoyas();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     Conectar cc=new Conectar();
 Connection cn= (Connection) cc.conexion();
 
      
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
txtCantidad.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
txtDescripcion.transferFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
txtCodigo.transferFocus();         // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
txtPrecio.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void tablaJoyasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJoyasMouseClicked
       DefaultTableModel model =  (DefaultTableModel) tablaJoyas.getModel();
       txtCantidad.setText(model.getValueAt(tablaJoyas.getSelectedRow(),0)+"");
       txtDescripcion.setText(model.getValueAt(tablaJoyas.getSelectedRow(),1)+"");
       txtCodigo.setText(model.getValueAt(tablaJoyas.getSelectedRow(),2)+"");
       txtPrecio.setText(model.getValueAt(tablaJoyas.getSelectedRow(),3)+"");
      
    }//GEN-LAST:event_tablaJoyasMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
 desbloquearjoyas();
        limpiarjoyas();
       
        txtCantidad.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablasJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablasJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablasJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablasJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablasJoyas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaJoyas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
